Repository jackfirth/rebellion, pull requests merged in 2019-12, with the labels that each got.

#360 Add into-transduced
  private/strict-cond.rkt
  private/transducer-pipe.rkt
  private/transducer-reducer-test.rkt
  private/transducer-reducer.rkt
  private/transducer.rkt
  private/transducer.scrbl
  streaming/transducer.rkt
  streaming/transducer/composition.rkt
Labels: enhancement

#365 Deduplicate transducer contracts
  private/transducer-base.rkt
  private/transducer.rkt
Labels: performance

#366 Move the impossible function into Rebellion's public API
  base/impossible-function.rkt
  private/base.scrbl
  private/impossible-function.rkt
  private/impossible-function.scrbl
  private/transducer-deduplicating.rkt
  private/transducer-enumerating.rkt
  private/transducer-pipe.rkt
  private/transducer-sorting.rkt
  private/transducer.rkt
Labels: enhancement

#367 Add batching-into-entries
  private/entry.rkt
  private/entry.scrbl
Labels: enhancement

#368 Add vector builders
  collection/vector/builder.rkt
  private/collection.scrbl
  private/vector-builder.rkt
  private/vector-builder.scrbl
Labels: enhancement

#369 Add vector reducers
  collection/vector.rkt
  private/collection.scrbl
  private/vector.rkt
  private/vector.scrbl
Labels: enhancement

#371 Add #:descending? argument to sorting transducer
  private/transducer-sorting-test.rkt
  private/transducer-sorting.rkt
  private/transducer.scrbl
Labels: enhancement

#370 Add sub-range binder information to type definitions
  private/record-type.rkt
  private/reference-type.rkt
  private/singleton-type.rkt
  private/tuple-type.rkt
Labels: enhancement

#372 Add sequence->vector
  private/vector.rkt
  private/vector.scrbl
Labels: enhancement

#374 Add enum types
  private/enum-type-base.rkt
  private/enum-type-descriptor.rkt
  private/enum-type.rkt
  private/enum-type.scrbl
  private/keyset.scrbl
  private/type.scrbl
  type/enum.rkt
  type/enum/base.rkt
  type/enum/descriptor.rkt
Labels: enhancement

#375 Add range-bound constructor, and various cleanups
  private/range.rkt
  private/range.scrbl
Labels: cleanup, enhancement

#376 More range changes
  private/range.rkt
  private/range.scrbl
Labels: backwards incompatible, enhancement
