Repository jackfirth/rebellion, pull requests merged in 2019-10, with the labels that each got.

#247 More integration with sequences
  private/multiset.rkt
  private/multiset.scrbl
Labels: enhancement

#248 More multiset changes
  private/multiset.rkt
  private/multiset.scrbl
Labels: backwards incompatible, enhancement

#253 Reorganize multidict doc sections
  private/multidict.scrbl
Labels: documentation

#254 Add multidict-remove and multidict-remove-entry
  private/multidict.rkt
  private/multidict.scrbl
Labels: enhancement

#255 Add multidict-replace-values
  private/multidict.rkt
  private/multidict.scrbl
Labels: enhancement

#250 Add the byte-hamming-weight function
  private/byte.rkt
  private/byte.scrbl
Labels: enhancement

#259 doc: fix undefined tags
  private/association-list.scrbl
  private/custom-write.scrbl
  private/keyset.scrbl
  private/list.scrbl
  private/multidict.scrbl
  private/multiset.scrbl
  private/phase.scrbl
  private/record.scrbl
  private/reducer.scrbl
  private/scribble-cross-document-tech.rkt
  private/text.scrbl
  private/transducer.scrbl
  private/type.scrbl
Labels: documentation

#265 Add immutable-string-split
  private/immutable-string.rkt
  private/immutable-string.scrbl
Labels: enhancement

#266 Compute multiset-unique-elements ahead of time
  private/multiset.rkt
Labels: performance

#267 Add into-max and into-min reducers
  private/comparator.rkt
  private/comparator.scrbl
  private/reducer.rkt
  private/reducer.scrbl
Labels: enhancement

#268 Make bitstrings implement the sequence interface
  private/bitstring.rkt
  private/bitstring.scrbl
Labels: enhancement

#271 Add entry-based transducers and hash utils
  collection/hash.rkt
  private/entry.rkt
  private/entry.scrbl
  private/hash.rkt
  private/hash.scrbl
Labels: enhancement

#272 Fix docs for rebellion/collection/hash
  private/collection.scrbl
  private/hash.scrbl
Labels: documentation

#277 Document table-size function
  private/table.scrbl
Labels: documentation

#278 Various hash improvements
  private/hash.rkt
  private/hash.scrbl
Labels: enhancement

#279 Use a better example for combine-into-hash
  private/hash.scrbl
Labels: documentation

#280 Add batching transducer constructor
  private/reducer.rkt
  private/reducer.scrbl
  private/transducer-batching-test.rkt
  private/transducer-batching.rkt
  private/transducer.scrbl
  streaming/transducer.rkt
Labels: enhancement

#281 Add deduplicating transducer
  private/transducer-deduplicating-test.rkt
  private/transducer-deduplicating.rkt
  private/transducer.scrbl
  streaming/transducer.rkt
Labels: enhancement

#284 Rename appending-into-list to append-into-list.
  private/list.rkt
  private/list.scrbl
Labels: backwards incompatible, cleanup

#288 Cleanup table implementation
  private/table.rkt
  private/table.scrbl
Labels: enhancement

#290 Delete CircleCI config
  .circleci/config.yml
Labels: cleanup

#293 Cleanup custom write code and API
  custom-write/struct.rkt
  custom-write/tuple.rkt
  private/custom-write-struct.rkt
  private/custom-write-tuple.rkt
  private/custom-write.rkt
  private/custom-write.scrbl
  private/singleton-type-descriptor.rkt
  private/tuple-type-base.rkt
Labels: backwards incompatible, cleanup

#295 Remove immutable-set? definitions
  private/association-list.rkt
  private/association-list.scrbl
  private/multidict.rkt
  private/multidict.scrbl
  private/multiset.rkt
  private/multiset.scrbl
Labels: cleanup

#297 Add set reducers
  collection/set.rkt
  private/collection.scrbl
  private/set.rkt
  private/set.scrbl
Labels: enhancement

#298 Add sorting transducer
  private/impossible.rkt
  private/transducer-deduplicating.rkt
  private/transducer-sorting-test.rkt
  private/transducer-sorting.rkt
  private/transducer.rkt
  private/transducer.scrbl
  streaming/transducer.rkt
Labels: enhancement, very complex

#302 Add grouping transducer
  private/entry.rkt
  private/entry.scrbl
Labels: enhancement

#307 Add into-line reducer
  private/reducer.rkt
  private/reducer.scrbl
Labels: enhancement

#308 Add enumerating transducer
  private/transducer-enumerating-test.rkt
  private/transducer-enumerating.rkt
  private/transducer.scrbl
  streaming/transducer.rkt
Labels: enhancement

#311 Make deduplicating a function instead of a constant
  private/transducer-deduplicating-test.rkt
  private/transducer-deduplicating.rkt
  private/transducer.scrbl
Labels: backwards incompatible

#312 Add into-for-each reducer constructor
  private/reducer.rkt
  private/reducer.scrbl
Labels: enhancement

#313 Add into-byte reducer
  private/byte.rkt
  private/byte.scrbl
Labels: enhancement

#316 Add equivalence relations
  base/equivalence-relation.rkt
  private/base.scrbl
  private/equivalence-relation.rkt
  private/equivalence-relation.scrbl
Labels: enhancement

#317 Add hash-key-set
  private/hash.rkt
  private/hash.scrbl
Labels: enhancement

#318 Add more deduplication transducers
  private/transducer-deduplicating-test.rkt
  private/transducer-deduplicating.rkt
  private/transducer.scrbl
Labels: enhancement

#321 Add in-option sequence constructor
  private/option.rkt
  private/option.scrbl
Labels: enhancement

#322 Add append mapping entry transducers
  private/entry.rkt
  private/entry.scrbl
Labels: enhancement

#323 Add a missing for-label import
  private/media.scrbl
Labels: documentation

#325 Add predicate-testing reducers
  private/reducer.rkt
  private/reducer.scrbl
Labels: enhancement

#329 Add peeking transducer
  private/transducer.rkt
  private/transducer.scrbl
Labels: enhancement

#330 Rework docs for peeking transducer
  private/transducer.scrbl
Labels: documentation
